# Generated by Django 4.2.11 on 2024-04-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('country_name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
